package firstgui;

/**
 *
 * @author Carson Schultz
 */
public class TempConverter extends javax.swing.JFrame {

    /**
     * Creates new form TempConverter
     */
    public TempConverter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPleaseEnterTemp = new javax.swing.JLabel();
        lblConvertTemp = new javax.swing.JLabel();
        btnConvertTemp = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        txtInputTemp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPleaseEnterTemp.setText("Please Enter The Temperature in Farenheight: ");

        lblConvertTemp.setText("Converted Temperature: ");

        btnConvertTemp.setLabel("Convert Temp");
        btnConvertTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertTempActionPerformed(evt);
            }
        });

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        txtInputTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputTempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConvertTemp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnQuit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblConvertTemp)
                            .addComponent(lblPleaseEnterTemp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtInputTemp, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPleaseEnterTemp)
                    .addComponent(txtInputTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConvertTemp)
                    .addComponent(btnQuit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(lblConvertTemp)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConvertTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertTempActionPerformed
        double temp = Integer.parseInt(txtInputTemp.getText());
        double convertedTemp = ((temp - 32) * (5 / 9));
        lblConvertTemp.setText(convertedTemp + " Centigrade."+ temp);
    }//GEN-LAST:event_btnConvertTempActionPerformed

    private void txtInputTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputTempActionPerformed
        // TODO add your handling code here:double temp = Integer.parseInt(txtInputTemp.getText());
    }//GEN-LAST:event_txtInputTempActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertTemp;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel lblConvertTemp;
    private javax.swing.JLabel lblPleaseEnterTemp;
    private javax.swing.JTextField txtInputTemp;
    // End of variables declaration//GEN-END:variables
}
